CREATE TABLE IF NOT EXISTS master_peralatan (
    uuid CHAR(36) PRIMARY KEY,
    nama_peralatan VARCHAR(120) NOT NULL UNIQUE,
    jenis VARCHAR(80) NOT NULL,
    ukuran VARCHAR(40) NULL,
    jumlah INT NOT NULL DEFAULT 0,
    kondisi VARCHAR(40) NOT NULL DEFAULT 'Baik',
    status VARCHAR(40) NOT NULL DEFAULT 'Tersedia',
    keterangan VARCHAR(255) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
